### PR TITLE
Frankreed/pfp caching

### PR DESCRIPTION
**Pull request by FrankreedX**
Pfp can be really heavy, this replaces the current Image tag with expo-image's Image tag, which has better caching.

Should I replace every Image tag with this?

### CODE REVIEW

**Comment by solderq35** [comment]
for testing: compare how long it takes for pfp to load for a user (on second visit) on profile tab index, team tab index

**Comment by solderq35** [comment]
https://github.com/Golf-Drill-Challenge-App/Golf-App/pull/194#issuecomment-2092047234

So was this something you were planning to include in this PR, integrating TanStack for caching?

**Review by solderq35 — CHANGES_REQUESTED** [review]
Got this error (**Android only, didn't get the error on iOS**) on team tab (tested on both a user with a pfp and a user without).

image
image

`
Cannot set prop 'borderRadius' on view 'class abi49_0_0.expo.modules.image.ExpoImageViewWrapper'
→ Caused by: abi49_0_0.com.facebook.react.bridge.UnexpectedNativeTypeException: Value for borderRadius cannot be cast from 
String to Double
`

**Comment by FrankreedX** [comment]
I'll prob get rid of this PR because expo-image is not good

**Pull request closed without merging**
