### PR TITLE
Gehrkej/ Stroke Error Handling

### PR DESCRIPTION
**Pull request by Gehrkej**
### Changes:
---
This PR introduces error handling for the strokes input and confirms that it is a positive integer.

**Related Issues:** #276 

### Screenshots:
--- 
image
image
image

### CODE REVIEW

**Comment by FrankreedX** [comment]
I noticed that we now have 3 different error check functions for the input form and it’s likely there’ll be more so let’s standardize the names. Maybe “check + [thing we’re checking]”?

**Review by FrankreedX — CHANGES_REQUESTED** [review]
Either merge all input validation into a function or rename the 3 input checking functions to be consistent. Having “validateInput” next to “validateStrokeInput” sounds like validateInput is not doing its job or Strokes is not an input

**Review by FrankreedX — APPROVED** [review]
Lgtm!

**Comment by solderq35** [comment]
Not that it matters because it's the same value in the end, but inputs like "2.0", "2.000" etc. go through without any warning message

image

**Review by solderq35 — APPROVED** [review]
LGTM, other than the minor issue mentioned above ("2.0" or similar trailing zero decimals will pass filter)

**Comment by solderq35** [comment]
Jake offered to add this readme typo fix to this PR.

Issue: https://github.com/Golf-Drill-Challenge-App/Golf-App/issues/278

**Pull request merged**
