### PR TITLE
Frankreed/show next shot

### LINKED ISSUE #255: Display next target
If there is 1 person entering data and 1 person golfing, it will be helpful for the golfing person to prep the next club while the data entering person enters data.
For this, the golfer needs to know what the next requirements are.

### PR DESCRIPTION
**Pull request by FrankreedX**
Screenshot 2024-06-05 at 4 46 21 PM

closes #255

### CODE REVIEW

**Review by Gehrkej — APPROVED** [review]
LGTM 👍

**Comment by solderq35** [comment]
Why are there so many commits tho

**Review by solderq35 — COMMENTED** [review]
image

Should "Next Shot" be a little bigger text? Other than that it look ok

**Review by solderq35 — APPROVED** [review]
LGTM. Maybe can fix the 99 commits tho, looks too high

**Comment by FrankreedX** [comment]
> LGTM. Maybe can fix the 99 commits tho, looks too high

It's probably either a rebase mistake or a merge thing... I don't think it's worth it to fix

**Comment by FrankreedX** [comment]
> image
> 
> Should "Next Shot" be a little bigger text? Other than that it look ok

Maybe make it look like the Shot 1/20 text? Prob not as big tho

**Comment by Gehrkej** [comment]
For documentation purposes, this is what the restyled next shot looks like: 
image

**Pull request merged**
