### PR TITLE
Frankreed/Make most buttons white

### PR DESCRIPTION
**Pull request by FrankreedX**

### CODE REVIEW

**Review by hannacol — APPROVED** [review]

**Review by solderq35 — COMMENTED** [review]
Not sure which file this is from, but:

I got the warning upon logging in and going to plan screen (default page)

image

**Review by solderq35 — COMMENTED** [review]
Other errors (not sure)

image

**Comment by FrankreedX** [comment]
This error is in assignments. I usually get around it by just commenting the text, which makes the boxes in assignments empty. No idea why or how it happens... I thought it's universal

**Comment by solderq35** [comment]
> Other errors (not sure)
> 
> image

EDIT: This is because I was on an older user account on Android, it worked fine on a new account.

**Comment by solderq35** [comment]
> Not sure which file this is from, but:
> 
> I got the warning upon logging in and going to plan screen (default page)
> 
> image

Figured it out, simple solution to just add `()` to function call.

**Review by solderq35 — APPROVED** [review]
might look again later but the 2 console warnings I found I was able to fix / figure out

**Comment by solderq35** [comment]
Seems to also fix https://github.com/Golf-Drill-Challenge-App/Golf-App/issues/148

**Comment by solderq35** [comment]
I think this also fixes https://github.com/Golf-Drill-Challenge-App/Golf-App/issues/191

**Pull request merged**
