### PR TITLE
Hannacol/image modal

### PR DESCRIPTION
**Pull request by hannacol**
Changes to Drill Description Page
    - Images are laid out in a 2 column grid
    - When clicked, the image will popup and cover background in black
    - While in popup, you can swipe through all the images in an Image Carousel

### CODE REVIEW

**Comment by FrankreedX** [comment]
When you swipe on the carousel, the modal automatically pops up. Also, ideally, the modal should still be swipable, so that you don't have to dismiss the modal, swipe, then click again.

**Comment by hannacol** [comment]
> I've been thinking and a way to simplify the implementation of this is to use a grid of thumbnails to display the images, then when one of them is clicked on, then you open a full screen gallery with carousel support. This way you don't have to deal with janky carousel behavior on the main description screen. Look into libraries like https://github.com/georstat/react-native-image-gallery

That's a good idea. I'll try to implement that this week.

**Comment by solderq35** [comment]
https://github.com/Golf-Drill-Challenge-App/Golf-App/blob/hannacol/image_modal/app/content/drill/%5Bid%5D/description.js#L33

I recommend changing this line to `height={windowHeight - 150}` or something, right now with Carousel height being 100% height it covers up the close modal button I think.

The close button worked after I made that change (both iOS and Android).

Picked 150 as I saw it elsewhere in the code (https://github.com/Golf-Drill-Challenge-App/Golf-App/blob/hannacol/image_modal/app/content/drill/%5Bid%5D/description.js#L69), but pick whatever value is best.

**Comment by solderq35** [comment]
Edit: Changing zIndex may be better, as changing Carousel component height makes it so carousel can't be swiped from top of screen (line 135ish)

```js
          <TouchableOpacity
            style={{ padding: 20, position: "absolute", top: 20, left: 20, zIndex: 10}}
            onPress={closeModal}
          >
            <Text style={{ color: "white", fontSize: 18 }}>Close</Text>
          </TouchableOpacity>
          ```

**Review by FrankreedX — APPROVED** [review]
rebase then merge. Looks good

**Pull request merged**
